apiVersion: v1
kind: ConfigMap
metadata:
  name: supernova-config-production
  namespace: supernova-production
  labels:
    app: supernova-ai
    environment: production
    config-version: v1.0.0
    managed-by: supernova-config-manager
data:
  # Core Application Settings
  SUPERNOVA_ENV: "production"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  APP_NAME: "SuperNova AI"
  APP_VERSION: "1.0.0"

  # Database Configuration
  DATABASE_ENGINE: "postgresql"
  DB_POOL_SIZE: "20"
  DB_MAX_OVERFLOW: "30"
  DB_POOL_TIMEOUT: "30"
  DB_POOL_RECYCLE: "3600"
  DB_ECHO: "false"
  DB_ECHO_POOL: "false"
  DB_SSL_REQUIRED: "true"
  DB_CONNECTION_ENCRYPTION: "true"
  DB_QUERY_TIMEOUT: "30"
  DB_AUDIT_ENABLED: "true"

  # TimescaleDB Configuration
  TIMESCALE_ENABLED: "true"
  TIMESCALE_PORT: "5432"
  TIMESCALE_POOL_SIZE: "15"
  TIMESCALE_MAX_OVERFLOW: "25"
  TIMESCALE_POOL_TIMEOUT: "30"
  TIMESCALE_POOL_RECYCLE: "3600"
  TIMESCALE_CHUNK_INTERVAL: "1 day"
  TIMESCALE_COMPRESSION_ENABLED: "true"
  TIMESCALE_COMPRESSION_AFTER: "7 days"
  TIMESCALE_RETENTION_POLICY: "7 years"
  TIMESCALE_DROP_CHUNKS_AFTER: "7 years"
  TIMESCALE_ENABLE_AGGREGATES: "true"
  TIMESCALE_HOURLY_AGGREGATES: "true"
  TIMESCALE_DAILY_AGGREGATES: "true"
  TIMESCALE_WEEKLY_AGGREGATES: "true"
  TIMESCALE_BATCH_SIZE: "1000"
  TIMESCALE_SLOW_QUERY_THRESHOLD: "5.0"
  TIMESCALE_ENABLE_QUERY_STATS: "true"
  TIMESCALE_SSL_MODE: "require"

  # LLM Configuration
  LLM_ENABLED: "true"
  LLM_PROVIDER: "openai"
  LLM_MODEL: "gpt-4"
  LLM_TEMPERATURE: "0.2"
  LLM_MAX_TOKENS: "4000"
  LLM_TIMEOUT: "60"
  LLM_MAX_RETRIES: "3"
  LLM_RETRY_DELAY: "2.0"
  LLM_STREAMING: "true"
  LLM_CONTEXT_ENHANCEMENT: "true"
  LLM_CACHE_ENABLED: "true"
  LLM_CACHE_TTL: "3600"
  LLM_COST_TRACKING: "true"
  LLM_FALLBACK_ENABLED: "true"
  LLM_FALLBACK_PROVIDER: "anthropic"
  LLM_AUTO_FAILOVER: "true"
  LLM_HEALTH_CHECK_ENABLED: "true"
  LLM_HEALTH_CHECK_INTERVAL: "300"
  LLM_FAILOVER_THRESHOLD: "3"
  LLM_FAILOVER_COOLDOWN: "900"
  LLM_CONCURRENT_REQUESTS_MAX: "50"

  # OpenAI Configuration
  OPENAI_BASE_URL: "https://api.openai.com/v1"
  OPENAI_DEFAULT_MODEL: "gpt-4"
  OPENAI_FALLBACK_MODEL: "gpt-3.5-turbo"
  OPENAI_CHAT_MODEL: "gpt-4"
  OPENAI_ANALYSIS_MODEL: "gpt-4"
  OPENAI_SUMMARY_MODEL: "gpt-3.5-turbo"
  OPENAI_EMBEDDING_MODEL: "text-embedding-3-small"
  OPENAI_MAX_REQUESTS_PER_MINUTE: "3000"
  OPENAI_MAX_TOKENS_PER_MINUTE: "150000"
  OPENAI_BATCH_SIZE: "10"
  OPENAI_GPT4_INPUT_COST: "0.03"
  OPENAI_GPT4_OUTPUT_COST: "0.06"
  OPENAI_GPT35_INPUT_COST: "0.0015"
  OPENAI_GPT35_OUTPUT_COST: "0.002"
  OPENAI_DAILY_COST_LIMIT: "30.00"

  # Anthropic Configuration
  ANTHROPIC_BASE_URL: "https://api.anthropic.com"
  ANTHROPIC_DEFAULT_MODEL: "claude-3-opus-20240229"
  ANTHROPIC_FALLBACK_MODEL: "claude-3-sonnet-20240229"
  ANTHROPIC_CHAT_MODEL: "claude-3-opus-20240229"
  ANTHROPIC_ANALYSIS_MODEL: "claude-3-opus-20240229"
  ANTHROPIC_SUMMARY_MODEL: "claude-3-sonnet-20240229"
  ANTHROPIC_MAX_REQUESTS_PER_MINUTE: "1000"
  ANTHROPIC_MAX_TOKENS_PER_MINUTE: "100000"
  ANTHROPIC_BATCH_SIZE: "5"
  ANTHROPIC_OPUS_INPUT_COST: "0.015"
  ANTHROPIC_OPUS_OUTPUT_COST: "0.075"
  ANTHROPIC_SONNET_INPUT_COST: "0.003"
  ANTHROPIC_SONNET_OUTPUT_COST: "0.015"
  ANTHROPIC_HAIKU_INPUT_COST: "0.00025"
  ANTHROPIC_HAIKU_OUTPUT_COST: "0.00125"
  ANTHROPIC_SAFETY_LEVEL: "strict"
  ANTHROPIC_CONTENT_FILTER: "true"
  ANTHROPIC_DAILY_COST_LIMIT: "20.00"

  # Security Configuration
  JWT_ALGORITHM: "HS256"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "15"
  JWT_REFRESH_TOKEN_EXPIRE_DAYS: "7"
  JWT_ISSUER: "supernova-ai-production"
  JWT_AUDIENCE: "supernova-clients"
  JWT_REQUIRE_CLAIMS: '["sub", "exp", "iat", "aud", "iss"]'
  JWT_BLACKLIST_ENABLED: "true"
  MFA_ENABLED: "true"
  MFA_ISSUER_NAME: "SuperNova AI"
  MFA_BACKUP_CODES_COUNT: "10"
  TOTP_DRIFT_SECONDS: "30"
  PASSWORD_MIN_LENGTH: "12"
  PASSWORD_REQUIRE_UPPERCASE: "true"
  PASSWORD_REQUIRE_LOWERCASE: "true"
  PASSWORD_REQUIRE_DIGITS: "true"
  PASSWORD_REQUIRE_SPECIAL: "true"
  PASSWORD_HASH_ROUNDS: "12"
  PASSWORD_HISTORY_COUNT: "10"
  PASSWORD_MAX_AGE_DAYS: "90"
  LOGIN_MAX_ATTEMPTS: "5"
  LOCKOUT_DURATION_MINUTES: "30"
  LOCKOUT_ESCALATION_ENABLED: "true"
  SESSION_TIMEOUT_MINUTES: "30"
  CONCURRENT_SESSIONS_LIMIT: "3"
  API_KEY_ENCRYPTION_ENABLED: "true"
  API_KEY_ROTATION_ENABLED: "true"
  API_KEY_ROTATION_DAYS: "90"
  API_KEY_LENGTH: "32"
  API_KEY_PREFIX: "sn_prod_"
  API_KEY_EXPIRY_DAYS: "365"
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_PER_MINUTE: "100"
  RATE_LIMIT_PER_HOUR: "1000"
  RATE_LIMIT_PER_DAY: "10000"
  RATE_LIMIT_BURST: "20"
  SSL_REQUIRED: "true"
  TLS_VERSION_MIN: "1.2"
  TLS_VERSION_PREFERRED: "1.3"
  HSTS_MAX_AGE: "31536000"
  HSTS_INCLUDE_SUBDOMAINS: "true"
  CORS_ALLOWED_ORIGINS: '["https://dashboard.supernova-ai.com", "https://app.supernova-ai.com"]'
  CORS_ALLOWED_METHODS: '["GET", "POST", "PUT", "DELETE", "OPTIONS"]'
  CORS_ALLOWED_HEADERS: '["Authorization", "Content-Type", "X-API-Key", "X-Request-ID", "X-CSRF-Token"]'
  CORS_ALLOW_CREDENTIALS: "true"
  CORS_MAX_AGE: "86400"
  MAX_REQUEST_SIZE_MB: "10"
  MAX_UPLOAD_SIZE_MB: "100"

  # Data Encryption
  ENCRYPTION_ALGORITHM: "AES-256-GCM"
  FIELD_ENCRYPTION_ENABLED: "true"
  DATABASE_ENCRYPTION_ENABLED: "true"
  BACKUP_ENCRYPTION_ENABLED: "true"
  KEY_ROTATION_ENABLED: "true"
  KEY_ROTATION_DAYS: "30"
  KEY_DERIVATION_ITERATIONS: "100000"

  # Cache Configuration
  CACHE_BACKEND: "redis"
  CACHE_DEFAULT_TTL: "3600"
  REDIS_MAX_CONNECTIONS: "50"
  REDIS_SOCKET_TIMEOUT: "5"
  RESPONSE_CACHE_TTL: "3600"
  RESPONSE_CACHE_MAX_SIZE: "10000"
  CONTEXT_CACHE_TTL: "1800"

  # Logging Configuration
  LOG_FORMAT: "json"
  LOG_FILE_ENABLED: "true"
  LOG_FILE_PATH: "/var/log/supernova/supernova.log"
  LOG_MAX_SIZE: "100MB"
  LOG_BACKUP_COUNT: "20"
  SECURITY_LOGGING_ENABLED: "true"
  AUDIT_LOG_RETENTION_DAYS: "2555"
  SECURITY_LOG_LEVEL: "INFO"
  LOG_SENSITIVE_DATA: "false"
  LOG_ENCRYPTION_ENABLED: "true"

  # Metrics Configuration
  METRICS_ENABLED: "true"
  METRICS_PORT: "9090"
  PROMETHEUS_ENABLED: "true"
  METRICS_EXPORT_ENABLED: "true"
  HEALTH_CHECK_ENABLED: "true"
  HEALTH_CHECK_INTERVAL: "60"
  ALERTING_ENABLED: "true"
  ALERT_EMAIL_ENABLED: "true"
  PERFORMANCE_MONITORING_ENABLED: "true"
  SLOW_QUERY_THRESHOLD: "5.0"
  ENABLE_QUERY_STATS: "true"

  # Performance Configuration
  MAX_CONCURRENT_REQUESTS: "200"
  ASYNC_TIMEOUT: "120"
  BACKGROUND_TASKS_ENABLED: "true"
  TASK_QUEUE_SIZE: "2000"
  MAX_CONCURRENT_TASKS: "50"
  HTTP_TIMEOUT: "30"
  WEBSOCKET_TIMEOUT: "600"
  DATABASE_TIMEOUT: "30"
  WS_AUTHENTICATION_REQUIRED: "true"
  WS_MAX_CONNECTIONS_PER_USER: "5"
  WS_MESSAGE_SIZE_LIMIT: "65536"
  WS_RATE_LIMIT_MESSAGES_PER_SECOND: "10"
  WS_CONNECTION_TIMEOUT: "300"
  LLM_REQUEST_LOGGING: "true"
  LLM_RESPONSE_LOGGING: "false"
  LLM_ERROR_LOGGING: "true"
  LLM_PERFORMANCE_LOGGING: "true"

  # Backup and Recovery
  CONFIG_BACKUP_ENABLED: "true"
  CONFIG_BACKUP_INTERVAL: "21600"
  CONFIG_BACKUP_PATH: "/backup/config"
  API_KEY_BACKUP_ENABLED: "true"
  API_KEY_BACKUP_ENCRYPTED: "true"
  DB_BACKUP_ENABLED: "true"
  DB_BACKUP_RETENTION_DAYS: "90"
  BACKUP_ENCRYPTION_REQUIRED: "true"
  DISASTER_RECOVERY_ENABLED: "true"
  RTO_TARGET_HOURS: "4"
  RPO_TARGET_HOURS: "1"

  # Compliance Configuration
  GDPR_COMPLIANCE_ENABLED: "true"
  CCPA_COMPLIANCE_ENABLED: "true"
  SOC2_COMPLIANCE_ENABLED: "true"
  PCI_DSS_COMPLIANCE_ENABLED: "true"
  FINRA_COMPLIANCE_ENABLED: "true"
  USER_DATA_RETENTION_DAYS: "2555"
  TRANSACTION_DATA_RETENTION_DAYS: "2555"
  LOG_DATA_RETENTION_DAYS: "2555"
  BACKUP_RETENTION_DAYS: "2555"
  DATA_ANONYMIZATION_ENABLED: "true"
  RIGHT_TO_BE_FORGOTTEN_ENABLED: "true"
  CONSENT_MANAGEMENT_ENABLED: "true"
  COOKIE_CONSENT_REQUIRED: "true"
  AUDIT_LOGGING_ENABLED: "true"
  INCIDENT_RESPONSE_ENABLED: "true"
  AUTO_INCIDENT_CREATION: "true"
  INCIDENT_SEVERITY_LEVELS: '["LOW", "MEDIUM", "HIGH", "CRITICAL"]'
  INCIDENT_NOTIFICATION_THRESHOLD: "MEDIUM"
  BREACH_NOTIFICATION_ENABLED: "true"
  BREACH_NOTIFICATION_HOURS: "72"
  BREACH_ASSESSMENT_REQUIRED: "true"

  # Feature Flags
  ENABLE_SENTIMENT_ANALYSIS: "true"
  ENABLE_BACKTESTING: "true"
  ENABLE_CHAT_INTERFACE: "true"
  ENABLE_API_ENDPOINTS: "true"
  ENABLE_PREFECT_WORKFLOWS: "true"
  ENABLE_VECTORBT_STRATEGIES: "true"
  ENABLE_TIMESCALE_ANALYTICS: "true"
  ENABLE_PAPER_TRADING: "true"
  ENABLE_MFA: "true"
  ENABLE_AUDIT_LOGGING: "true"
  ENABLE_RATE_LIMITING: "true"
  ENABLE_IP_FILTERING: "true"
  ENABLE_METRICS: "true"
  ENABLE_TRACING: "true"
  ENABLE_PROFILING: "false"
  ENABLE_ERROR_TRACKING: "true"
  ENABLE_EXPERIMENTAL_FEATURES: "false"
  ENABLE_BETA_LLM_FEATURES: "false"
  ENABLE_DEBUG_FEATURES: "false"

  # Deployment Configuration
  DEPLOYMENT_ENVIRONMENT: "production"
  CONTAINER_MODE: "true"
  CONTAINER_PLATFORM: "kubernetes"
  K8S_NAMESPACE: "supernova-production"
  K8S_SERVICE_ACCOUNT: "supernova-prod-sa"
  DATA_VOLUME: "/app/data"
  LOGS_VOLUME: "/var/log/supernova"
  CONFIG_VOLUME: "/app/config"
  SECRETS_VOLUME: "/app/secrets"
  BACKUP_VOLUME: "/backup"
  MEMORY_LIMIT: "4Gi"
  CPU_LIMIT: "2000m"
  MEMORY_REQUEST: "2Gi"
  CPU_REQUEST: "1000m"
  REPLICA_COUNT: "3"
  MAX_UNAVAILABLE: "1"
  MAX_SURGE: "1"

  # Network Configuration
  API_BASE_URL: "https://api.supernova-ai.com"
  FRONTEND_URL: "https://dashboard.supernova-ai.com"
  WEBSOCKET_URL: "wss://ws.supernova-ai.com"
  LOAD_BALANCER_ENABLED: "true"
  HEALTH_CHECK_PATH: "/health"
  READINESS_PROBE_PATH: "/ready"
  LIVENESS_PROBE_PATH: "/health"
  CDN_ENABLED: "true"

  # Monitoring Integrations
  APM_ENABLED: "true"
  APM_SERVICE_NAME: "supernova-ai-production"
  APM_ENVIRONMENT: "production"
  ERROR_TRACKING_ENABLED: "true"
  LOG_AGGREGATION_ENABLED: "true"
  TRACING_ENABLED: "true"
  TRACING_SAMPLE_RATE: "0.1"

  # Environment Validation
  CONFIG_VALIDATION_ENABLED: "true"
  CONFIG_VALIDATION_STRICT_MODE: "true"
  CONFIG_HOT_RELOAD_ENABLED: "false"
  PRODUCTION_VALIDATION_RULES: "true"
  SECURITY_VALIDATION_ENABLED: "true"
  COMPLIANCE_VALIDATION_ENABLED: "true"

  # Emergency Procedures
  CIRCUIT_BREAKER_ENABLED: "true"
  CIRCUIT_BREAKER_FAILURE_THRESHOLD: "5"
  CIRCUIT_BREAKER_RECOVERY_TIMEOUT: "300"
  EMERGENCY_SHUTDOWN_ENDPOINT: "/emergency/shutdown"
  MAINTENANCE_MODE_ENABLED: "false"
  MAINTENANCE_MESSAGE: "SuperNova AI is currently undergoing scheduled maintenance."

  # External APIs Rate Limiting
  TWITTER_RATE_LIMIT: "0.5"
  REDDIT_RATE_LIMIT: "1.0"
  NEWS_RATE_LIMIT: "2.0"
  REDDIT_USER_AGENT: "SuperNovaAI-Production/1.0"

  # Cloud Secrets Management
  SECRETS_STORAGE_PATH: "/app/secrets"
  ENABLE_CLOUD_SECRETS: "true"
  AWS_SECRETS_MANAGER_ENABLED: "true"